/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CrudTable {
    }
    interface L4Button {
        "buttonText": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLCrudTableElement extends Components.CrudTable, HTMLStencilElement {
    }
    var HTMLCrudTableElement: {
        prototype: HTMLCrudTableElement;
        new (): HTMLCrudTableElement;
    };
    interface HTMLL4ButtonElement extends Components.L4Button, HTMLStencilElement {
    }
    var HTMLL4ButtonElement: {
        prototype: HTMLL4ButtonElement;
        new (): HTMLL4ButtonElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "crud-table": HTMLCrudTableElement;
        "l4-button": HTMLL4ButtonElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface CrudTable {
    }
    interface L4Button {
        "buttonText"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "crud-table": CrudTable;
        "l4-button": L4Button;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "crud-table": LocalJSX.CrudTable & JSXBase.HTMLAttributes<HTMLCrudTableElement>;
            "l4-button": LocalJSX.L4Button & JSXBase.HTMLAttributes<HTMLL4ButtonElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
